name: LEMP-stack / Monitoring CI

on:
  push:
    branches: 
      - main

  pull_request:

jobs: 
  integration-test:
    runs-on: ubuntu-latest

    steps: 

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build containers
        run: docker compose build

      - name: Starting stack
        run: docker compose up -d

      - name: Waiting for startup
        run: sleep 30

      - name: Show running containers
        run: docker compose ps

      - name: Checking Nginx
        run: | 
          curl -f http://localhost

      - name: Checking WordPress
        run: |
          curl -f http://localhost/wp-admin

      - name: Checking Prometheus
        run: |
          curl -f http://localhost:9090/-/healthy

      - name: Checking Grafana
        run: |
          curl -f http://localhost:3030/api/health

      - name: Ckeck Node Exporter
        run: |
          curl -f http://localhost:9100/metrics
         
      - name: Showing container logs if pipeline failed
        if: failure()
        run: docker compose logs

      - name: Cleanup
        if: always()
        run: docker compose down -v







