name: Infrastructure CI

on:
  push:
    branches:
      - main
  
  pull_request:

jobs:
  validate configs:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate nginx configuration
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/nginx/default.conf:/etc/nginx/default.conf:ro \
          nginx:latest \
          nginx -t

      - name: Validate prometheus configuration
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro \
          prom/prometheus:v3.12.0 \
          --config.file=/etc/prometheus/prometheus.yml

      - name: Validate Docker Compose
        run: docker compose config

  build:
    runs-on: ubuntu-latest
      needs: validate configs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build
